package com.example.socialmediaapp.services;

public interface ServiceConstant {

    public static final String ACTION_CARD_GET_LIST = "cardGetList_v8";
    public static final String ACTION_OUTLET_DETAILS = "outletLocatorDetails3";
    public static final String ACTION_OUTLET_LIST = "outletLocatorList3";
    public static final String ACTION_GET_CARD_TYPE_BY_CARD_NO = "cardGetCardType6";
    public static final String ACTION_PROFILE_FORGOT_PWD = "profileForgotIDPsw4";
    public static final String ACTION_PROFILE_LOGIN = "profileLogin4";
    public static final String ACTION_SEND_REG_OTP = "SendRegOTP_v5";
    public static final String ACTION_REG_OTP_CONFIRMATION = "RegOTPConfirmation_v2";
    //    public static final String ACTION_PROMOTION_BY_LOCATION = "promoByLocation5";//not using
    public static final String ACTION_USER_CARD_ADD = "cardRegister_v2";
    public static final String ACTION_USER_CARD_ADD_V = "cardRegisterV_v6";
    public static final String ACTION_USER_CARD_ADD_P = "cardRegisterP_v5";
    public static final String ACTION_USER_CARD_CHANGE_PIN = "cardPINChange3";
    //    public static final String ACTION_USER_CARD_DELETE = "cardDelete2";//not using
    public static final String ACTION_USER_CARD_GET_LIST = "profileCardGetList_v10";
    //    public static final String ACTION_USER_CARD_MEMBER_DETAILS_GET = "memberDetailGet_v3";//not using
    public static final String ACTION_USER_CARD_POINT_INQUIRY = "cardPointGet5";
    public static final String ACTION_USER_CARD_TRANSACTION = "cardTransactionGet5";
    public static final String ACTION_USER_CARD_TRANSACTION_REDEMPTION = "cardRedemptionGet6";
    public static final String ACTION_FEEDBACK = "profileFeedbacks3";
    public static final String ACTION_REDEMPTION = "cardRedeem_v5"; // "cardRedeem_v5";
    public static final String ACTION_REGISTER_MOBILE_ID = "MobileIdRegister3";
    public static final String ACTION_PLATFORM_UPDATE = "PlatformUpdate_v4";
    //    public static final String ACTION_PROMOTION_BY_CATEGORY_NEW = "promoCategoryListNew2";//not using
    public static final String ACTION_GET_SINGLE_PROMO = "getSinglePromotion_v4";
    public static final String ACTION_GET_NOTIFICATION_SENT = "GetNotificationSent_v5";
    public static final String ACTION_CHANGE_PASSWORD = "profileChangeIDPsw3";
    public static final String ACTION_PROMO_LIST_GET = "promoListGet3";
    public static final String ACTION_GET_VOUCHER_LIST_BY_CARD = "GetVoucherListByCard_v5";
    public static final String ACTION_GET_SINGLE_VOUCHER = "GetSingleVoucher_v5";
    public static final String ACTION_GENERATE_VOUCHER_OTP = "GenerateVoucherOTP4"; // "GenerateVoucherOTP4";
    public static final String ACTION_GET_VOUCHER_LOG = "GetVoucherLog5";
    //    public static final String ACTION_REWARD = "RewardByCardNo_v2";
//    public static final String ACTION_GET_TRANSACTION_LOG = "GetTransactionLogByCardNo_v2";
    public static final String ACTION_GET_CATEGORIZE_MERCHANT_HQ = "GetCategorizeClient_v3"; //GetCategorizeClient_v2
    public static final String ACTION_PROFILE_GET_DETAILS = "profileGetDetails_v5"; //v4
    public static final String ACTION_SEND_UPDATE_OTP = "SendUpdateOTP_v4";
    public static final String ACTION_UPDATE_OTP_CONFIRMATION = "UpdateOTPConfirmation_v3";
    public static final String ACTION_PROFILE_FORGOT_PIN = "profileForgotPIN_v2";
    public static final String ACTION_GET_CARD_REQUEST_LIST = "GetCardRequestList_v3";
    public static final String ACTION_GET_MERCHANT_HQ_CONTACT = "GetMerchantHQContact_v2";
    public static final String ACTION_PROFILE_IS_NEW = "profileIsNew_v5";
    public static final String ACTION_GET_ADDITIONAL_INFO_BY_CARD = "GetAdditionalInfoByCard_v2";
    public static final String ACTION_UPDATE_ADDITIONAL_INFO_BY_CARD = "UpdateAdditionalInfoByCard_v2";
    public static final String ACTION_GET_RACE_LIST = "getRaceList_v2";
    public static final String ACTION_GET_OCCUPATION_LIST = "getOccupationList_v2";
    public static final String ACTION_GET_STATE_LIST = "getStateList_v2";
    public static final String ACTION_GET_COUNTRY_LIST = "getCountryList_v2";
    public static final String ACTION_GET_GIFT_LIST_BY_CARD_NO = "GetGiftListByCardNo_v2";
    public static final String ACTION_REDEEM_GIFT = "RedeemGift_v2";
    public static final String ACTION_SWIPE_REDEEM_VOUCHER = "SwipeRedeemVoucher_v2";
    public static final String ACTION_END_SWIPE_VOUCHER = "EndSwipeVoucher_v2";
    public static final String ACTION_GET_REFERRAL_BY_CARD_TYPE = "getReferralByCardType_v2";
    public static final String ACTION_DELETE_ACCOUNT = "DeleteAccount_v3"; //v2
    public static final String ACTION_REDEMPTION_PIN_CHECK = "RedemptionPinCheck_v3";
    public static final String ACTION_GET_DISPLAY_NAME_BY_CLIENT = "GetDisplayNameByClient_v2";
    public static final String ACTION_PROFILE_LOGIN_GET_OTP = "profileLogin_GetOTP";
    public static final String ACTION_PROFILE_LOGIN_BY_OTP = "profileLogin_ByOTP";


    // Field
    public static final String TIMESTAMP = "TIMESTAMP";
    public static final String WSKEY = "WSKey";
    public static final String S_WSKEY = "wsKey";
    public static final String USER_NAME = "userName";
    public static final String EMAIL_MOBILE_SOCIAL_ID = "EmailMobileSocialID";
    public static final String EMAIL_MOBILE = "emailMobile";
    public static final String NAME = "name";
    public static final String USER_PASSWORD = "userPsw";
    public static final String LOGIN_ID = "loginId";
    public static final String USER_EMAIL = "userEmail";
    public static final String LOGIN_SOURCE = "loginSource";
    public static final String REG_ID = "regId";
    public static final String REG_SOURCE = "regSource";
    public static final String S_OTP = "otp";
    public static final String ID = "id";
    public static final String GUID = "GUID";
    public static final String PLATFORM_VERSION = "PlatformVersion ";
    public static final String MANUFACTURER = "Manufacturer";
    public static final String MODEL = "Model";
    public static final String APKVER = "APKVer";
    public static final String S_IMEI = "imei";
    public static final String IMEI = "IMEI";
    public static final String MOBILE_ID = "mobileID";
    public static final String C_MOBILE_ID = "MobileID";
    public static final String S_MOBILE_ID = "mobileId";
    public static final String MOBILE_TYPE = "mobileType";
    public static final String CARD_NO = "cardNo";
    public static final String CARD_PIN = "cardPIN";
    public static final String OLD_PIN = "oldPIN";
    public static final String PIN = "PIN";
    public static final String S_CLIENT = "client";
    public static final String CLIENT = "Client";
    public static final String CARD_TYPE = "cardType";
    public static final String CARD_TYPE_C = "CardType";
    public static final String REMARK = "remark";
    public static final String COMPANY_CODE = "companyCode";
    public static final String BRANCH_CODE = "branchCode";
    public static final String REDEMPTION_TYPE = "rType";
    public static final String AMOUNT = "amount";
    public static final String MERCHANT = "merchant";
    public static final String IMAGE_1 = "image1";
    public static final String IMAGE_2 = "image2";
    public static final String IMAGE_3 = "image3";
    public static final String COMPANY = "company";
    public static final String CATEGORY = "category";
    public static final String LATITUDE = "latitude";
    public static final String LONGITUDE = "longitude";
    public static final String RADIUS = "rodius";
    public static final String CARD_NUMBER = "cardNumber";
    public static final String PROMOTION_ID = "promotionID";
    public static final String START_INDEX = "startIndex";
    public static final String END_INDEX = "endIndex";
    public static final String NEW_PIN = "newPIN";
    public static final String MOBILE_PIN = "mobilePIN";
    public static final String CARD_HOLDER_NAME = "cardHolderName";
    public static final String ADDR_1 = "addr1";
    public static final String ADDR_2 = "addr2";
    public static final String ADDR_3 = "addr3";
    public static final String ZIP = "zip";
    public static final String STATE = "state";
    public static final String CITY = "city";
    public static final String COUNTRY = "country";
    public static final String EMAIL = "email";
    public static final String MOBILE_NO = "mobileNo";
    public static final String IC = "IC";
    public static final String BIRTH_DATE = "birthdate";
    public static final String GENDER = "gender";
    public static final String M_STATUS = "mStatus";
    public static final String CHILD_NO = "childNo";
    public static final String S_MOBILE = "mobile";
    public static final String MOBILE = "MOBILE";
    public static final String FEEDBACK = "feedbacks";
    public static final String MOBILE_ID_CAP = "MobileID";
    public static final String C_LAST_UPDATE_DATE = "LastUpdateDate";
    public static final String LAST_UPDATE_DATE = "lastUpdateDate";
    public static final String USER_OLD_PASSWORD = "userOldPassword";
    public static final String USER_NEW_PASSWORD = "userNewPassword";
    public static final String VOUCHER_ID = "voucherID";
    public static final String VOUCHER_MEMBER_ID = "voucherMemberID";
    public static final String CLIENT_CODE = "clientCode";
    public static final String SALES_DATE = "salesDate";
    public static final String C_MEMBER_ID = "MemberId";
    public static final String C_SALES_ID = "SalesId";
    public static final String C_SALES_DATE = "SalesDate"; //capital letter
    public static final String C_TOTAL_FINAL_AMOUNT = "TotalFinalAmount";
    public static final String C_TOTAL_POINT = "TotalPoint";
    public static final String C_RECEIPT_NO = "ReceiptNo";
    public static final String C_MERCHANT = "Merchant";
    public static final String C_RECEIPT_DATE = "ReceiptDate";
    public static final String PROCESS_DATE = "ProcessDate";
    public static final String C_STATUS = "Status";
    public static final String STATUS = "Status";
    public static final String C_REASON = "Reason";
    public static final String C_IMAGE_URL_1 = "ImageUrl1";
    public static final String C_IMAGE_URL_2 = "ImageUrl2";
    public static final String C_IMAGE_URL_3 = "ImageUrl3";

    public static final String ADDRESS = "Address";
    public static final String C_STATE = "State";
    public static final String C_COUNTRY = "Country";
    public static final String C_GENDER = "Gender";
    public static final String C_RACE = "Race";
    public static final String C_DESIGNATION = "Designation";
    public static final String C_MARITAL_STATUS = "MaritalStatus";
    public static final String GIFT_ID = "giftId";
    public static final String REFERRED_MOBILE_NO = "ReferredMobileNo";
    public static final String EN_DATA = "EnData";

    //reCAPTCHA REST API
    public static final String EVENT = "event";
    public static final String TOKEN = "token";
    public static final String SITE_KEY = "siteKey";
    public static final String EXPECTED_ACTION = "expectedAction";
    public static final String SIGNUP = "signup";

    //Huawei User Detect API  accessToken
    public static final String GRANT_TYPE = "grant_type";
    public static final String CLIENT_ID = "client_id";
    public static final String CLIENT_SECRET = "client_secret";
    public static final String ACCESSS_TOKEN = "accessToken";
    public static final String RESPONSE = "response";
    //public static final String CLIENT_ID = "clientID"; why got this clientID




}
